config/routes.rb
Rails.application.routes.draw do
  root "exhibits#index"
  resources :exhibits, only: [:index, :show]

  get "/validate_location", to: "exhibits#validate_location"
  get "/get_location", to: "exhibits#get_location"
  get "/get_high_score", to: "exhibits#get_high_score"
  put "/update_high_score", to: "exhibits#update_high_score"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :locations

  def find_locations(exhibit_id, size_id)
    self.locations.where(exhibit_id: exhibit_id, size_id: size_id)
  end
end

app/models/exhibit.rb
class Exhibit < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :character
  belongs_to :exhibit
  belongs_to :size

  def self.validate(character_id, exhibit_id, size_id, div_id)
    return true if Location.find_by("character_id = ? AND exhibit_id = ? AND size_id = ? AND div = ?", character_id, exhibit_id, size_id, div_id)

    return false
  end
end

app/models/size.rb
class Size < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exhibits_controller.rb
class ExhibitsController < ApplicationController
  def index
    @exhibits = Exhibit.all.order(:id)
  end

  def show
    @exhibit = Exhibit.find(params[:id])
  end

  def get_high_score
    @exhibit = Exhibit.find(exhibit_params[:exhibit_id])

    respond_to do |format|
      format.json { render :json => @exhibit.high_score }
    end
  end

  # PUT 
  def update_high_score
    @exhibit = Exhibit.find(exhibit_params[:exhibit_id])
    @exhibit.update(high_score: exhibit_params[:new_high_score])
    head :created
  end

  def validate_location
    @validated = Location.validate(
      exhibit_params[:character_id],
      exhibit_params[:exhibit_id], 
      exhibit_params[:size_id], 
      exhibit_params[:location_id]
    )

    respond_to do |format|
      format.json { render :json => @validated , status: :ok }
    end
  end

  def get_location
    @character = Character.find(exhibit_params[:character_id].to_i)
    @locations = @character.find_locations(
      exhibit_params[:exhibit_id],
      exhibit_params[:size_id]
    ).map { |location| location.div }

    respond_to do |format|
      format.json { render :json => @locations , status: :ok}
    end
  end

  def exhibit_params
    params.permit(
      :character_id,
      :exhibit_id,
      :size_id,
      :location_id,
      :new_high_score,
      :exhibit => {}
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
end

app/views/exhibits/index.html.erb
<%= content_for :javascript do %>
  <%= javascript_import_module_tag "index" %>
<% end %>

<div class="index-container">
  
  <h1>Choose an Exhibit</h1>

  <% @exhibits.each do |exhibit| %>
    <%= link_to exhibit_path(exhibit), data: {turbo: false}, class: "exhibit_#{exhibit.id}" do %>
      <div class="info">
        <p><%= exhibit.title %></p>

        <% if exhibit.id === 1 %>
          <p>Easy</p>
        <% elsif exhibit.id === 2 %>
          <p>Medium</p>
        <% else %>
          <p>Hard</p>
        <% end %>

        <p>Best Time: 
          <% if exhibit.high_score %>
            <%= exhibit.high_score %>
          <% else %>
            Not Yet Recorded
          <% end %>
        </p>
      </div>
      <%= image_tag exhibit.image_path %>
    <% end %>
  <% end %>

</div>

app/views/exhibits/show.html.erb
<%= content_for :javascript do %>
  <%= javascript_import_module_tag "exhibits" %>
<% end %>

<div class="page-content">
  <div class="top-panel">
    <nav>
      <%= link_to "Back To Exhibits", exhibits_path %>
    </nav>
  
    <div id="image-size">
      <%= form_with do |f| %>
        <h2>Image Size</h2>
        <p>*changing restarts the game</p>
        <div class="size-options">
          <div>
            <%= f.radio_button :size, "1" %>
            <%= f.label :image_size, "800x500 (small)" %>
          </div>
          <div>
            <%= f.radio_button :size, "2", checked: true %>
            <%= f.label :image_size, "1000x630 (medium)" %>
          </div>
          <div>
            <%= f.radio_button :size, "3" %>
            <%= f.label :image_size, "1200x750 (large)" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  
  <div class="exhibit-content">
    <div class="characters">
      <div class="waldo">
        <p>Waldo</p>
        <%= image_tag("waldo.png") %>
        <i class="fa-regular fa-circle-check fa-2xl"></i>
      </div>
      <div class="wilma">
        <p>Wilma</p>
        <%= image_tag("wilma.png") %>
        <i class="fa-regular fa-circle-check fa-2xl"></i>
      </div>
      <div class="wizard">
        <p>Wizard</p>
        <%= image_tag("wizard_whitebeard.png") %>
        <i class="fa-regular fa-circle-check fa-2xl"></i>
      </div>
      <div class="odlaw">
        <p>Odlaw</p>
        <%= image_tag("odlaw.png") %>
        <i class="fa-regular fa-circle-check fa-2xl"></i>
      </div>
    </div>
  
    <div class="right-panel">
      <div class="score-panel">
        <div id="high-score">
          <% if @exhibit.high_score %>
            <%= "Best time: " + @exhibit.high_score %>
          <% else %>
            <%= "Best time: --" %>
          <% end %>
        </div>
        <div id="timer">
          <div class="minutes">00</div>
          <div>:</div>
          <div class="seconds">00</div>
          <div class="score-msg"></div>
        </div>
  
      </div>
  
      <h1><%= @exhibit.title %></h1>
  
      <div id="image-grid-container">
        <div id="grid"></div>
        <%= image_tag(@exhibit.image_path, size: "1000x630") %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Where's Waldo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_import_module_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital@1&display=swap" rel="stylesheet"> 
    <script src="https://kit.fontawesome.com/8e6d986d17.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
    <%= yield :javascript %>
  </body>
</html>